### ISSUE TITLE
CI for ecs-logging-* projects

### ISSUE THREAD

**Issue by felixbarny** [elastic/ecs-logging#1]
Hey @kuisathaverat,

could you or someone from the automation team help to set up a CI Server for these projects?
The idea would be to have one or more repos for Java, PHP, .NET, Ruby, JavaScript, Python and go.

Do you think it makes sense to have a separate CI server for that or would you prefer to re-use the observability/apm-ci for that?

**Comment by kuisathaverat** [comment]
let's start in apm-ci, we can change anytime we need it.

**Comment by felixbarny** [comment]
Sounds good 👍🏻
So the owners of the language specific loggers will let you know when they need CI

**Comment by philkra** [comment]
FYI: @elastic/ecs-logging

**Comment by webmat** [comment]
For the record, the ECS repo is using Travis CI. I'd be happy to have ECS use this CI instead of Travis :-)

**Comment by webmat** [comment]
@felixbarny Did you accidentally close this issue? If this was intentional, is there another issue we can track?

**Comment by felixbarny** [comment]
This issue was about the general approach. I think there should be separate issues for each project that wants CI. I expect the requirements to be vastly different.
