### ISSUE TITLE
[Python] logging

### ISSUE THREAD

**Issue by philkra** [elastic/ecs-logging#12]
create an ECS formatter for python's [logging](https://docs.python.org/3/library/logging.html).

pinging @beniwohli & @basepi

**Comment by ypid-geberit** [comment]
Just some input on Python logging. We went with Python scripts logging to journald where journalbeat can be used. So you can potentially already use ECS with Python. Ref: https://github.com/geberit/elastic-helpers/blob/master/Logging%20best%20practices.md#python

The issue is related to: #13

**Comment by sethmlarson** [comment]
I'd assign myself but I am not able to, permission issue probably :)

**Comment by sethmlarson** [comment]
Completed in https://github.com/elastic/ecs-logging-python/pull/1
