### ISSUE TITLE
zap

### ISSUE THREAD

**Issue by philkra** [elastic/ecs-logging#15]
Formatter for zap

pinging @axw & @karmi

**Comment by simitt** [comment]
@philkra I started working on this, but do not have the permissions to assign myself, could you please assign me or change the permissions. Thank you.

**Comment by philkra** [comment]
@simitt , I added you to the team, should have the proper permissions now. Can you confirm?

**Comment by simitt** [comment]
Yes, I have permissions now, thank you.

**Comment by felixbarny** [comment]
As there's https://github.com/elastic/ecs-logging-go-zap, can this be closed?
