### ISSUE TITLE
[Go] zerolog

### ISSUE THREAD

**Issue by philkra** [elastic/ecs-logging#16]
ECS formatter for zerlog

pinging @axw & @karmi

**Comment by michel-laterman** [comment]
I've created a private repo for this and have a PR for feedback: https://github.com/elastic/ecs-logging-go-zerolog/pull/1
@simitt, can you please take a look and tell me if I'm missing something?

**Comment by michel-laterman** [comment]
@philkra, do you think we should close this issue now that we have the initial implementation?
