### ISSUE TITLE
[Meta] General Availability

### ISSUE THREAD

**Issue by felixbarny** [elastic/ecs-logging#27]
- Missing ECS loggers
  - [Ruby](https://github.com/elastic/ecs-logging/issues?q=is%3Aissue+is%3Aopen+label%3Alang%3Aruby)
  - Go: [logrus](https://github.com/elastic/ecs-logging/issues/14) and [zerolog](https://github.com/elastic/ecs-logging/issues/16)
- Ensure all loggers comply with spec
  - Validate against the [spec](https://github.com/elastic/ecs-logging/blob/master/spec/spec.json) (example: https://github.com/elastic/ecs-logging-java/pull/111)
  - Ensure loggers integrate with APM by adding `trace.id` and `transaction.id` identifiers (see also [#29](https://github.com/elastic/ecs-logging/pull/29/files))
- Dotted field names: `dot_expand` Filebeat processor to deal with dotted field names like `log.level` ~https://github.com/elastic/beats/pull/20489~ -> https://github.com/elastic/beats/pull/22849
- Review external licenses & OSS compliance
- Docs
  - Add documentation for each logger on elastic.co (example: https://github.com/elastic/ecs-logging-java/pull/112, [live docs](https://www.elastic.co/guide/en/ecs-logging/java/current/index.html))
  - Cross-links from Filebeat and APM log correlation documentation

### Implementation Status
Language | Milestone / Issue | Impl. Done | Passes Spec validation | OSS compliance | Docs Done 
---|---|---|---|---|---
Java | [ecs-logging-java/milestone/1](https://github.com/elastic/ecs-logging-java/milestone/1) | ✅  | ✅ | ✅ | ✅ 
PHP |   |  ✅  | ✅ | ✅ | ✅ 
.NET | https://github.com/elastic/ecs-dotnet/issues/119  | ✅  | ✅ | ✅  | ✅ 
JavaScript |  https://github.com/elastic/apm-agent-nodejs/issues/1874 |✅  | ✅ | ✅ | ✅ 
Python |  https://github.com/elastic/ecs-logging-python/issues/26 |  ✅ | ✅ |  ✅ | ✅
Go |  <ul><li>https://github.com/elastic/ecs-logging-go-zap/issues/19</li><li>https://github.com/elastic/ecs-logging-go-logrus/issues/4</li></ul>| ✅ | ✅  | ✅ | ✅  
Ruby | https://github.com/elastic/ecs-logging/issues/8 | ✅ | ✅   | ✅   | ✅

**Comment by felixbarny** [comment]
Tagging @andresrc to kindly help with coordinating the documentation efforts

**Comment by russcam** [comment]
Ticked the boxes for the .NET agent: opened https://github.com/elastic/ecs-dotnet/pull/120 and https://github.com/elastic/ecs-dotnet/pull/121 for docs and validation, respectively, and have checked OSS compliance.

**Comment by trentm** [comment]
Ticked the boxes for Node.js. The OSS compliance issue is done but not reviewed.

**Comment by trentm** [comment]
> The OSS compliance issue is done but not reviewed.

It is reviewed and closed now.

**Comment by basepi** [comment]
Re-ticked the OSS compliance box for Python.
