### ISSUE TITLE
Add ECS logging overview documentation

### ISSUE THREAD

**Issue by felixbarny** [elastic/ecs-logging#31]
We have started to put the documentation for the individual loggers to the [elastic.co website](https://www.elastic.co/guide/en/ecs-logging/java/current/index.html).

Similar to the overview docs in APM, I think it makes sense that we have an overview page for ECS loggers that describe at a high level what ECS loggers are, what benefits they have, and link to the individual language loggers.

This can serve as a canonical page when linking from other parts of our docs, such as from the Filebeat docs.

I guess we could use some of the things that are written in the [overview page of the ecs-logging-java docs](https://www.elastic.co/guide/en/ecs-logging/java/current/intro.html). The question is if we want to duplicate some of the information, link to the generic overview docs, or have the docs for the individual loggers be sub-sections of the global docs. 

@bmorelli25 do you have an opinion on that?

**Comment by bmorelli25** [comment]
> Similar to the overview docs in APM, I think it makes sense that we have an overview page for ECS loggers that describe at a high level what ECS loggers are, what benefits they have, and link to the individual language loggers.

Makes sense to me as well.

> The question is if we want to duplicate some of the information, link to the generic overview docs, or have the docs for the individual loggers be sub-sections of the global docs.

The short answer is that we have no perfect solution for this. The longer answer is. . .

When you say "sub-sections", do you mean that all of the content for all ECS loggers would be in the same documentation book? If so, I think this is the best solution, but it would require all of the loggers to share versioning. Is that realistic?

Linking to the generic docs works, but would put us in the same scenario we have now with the APM Agents -- content in many different books, with users presumably needing to view at least two books (overview + language) to gain all the required information.

We could duplicate without duplicating. Have the `ecs-logging` repo be the source of truth for all generic ECS logging content. We can use include directives to include shared content in each of the `ecs-logging-*` documentation repositories. This would allow us to reuse content where necessary, without having to maintain generic content in multiple documentation books.

**Comment by felixbarny** [comment]
> it would require all of the loggers to share versioning. Is that realistic?

Good point. No, that's not realistic.

> We could duplicate without duplicating.

Sounds promising
