### ISSUE TITLE
Serilog

### ISSUE THREAD

**Issue by philkra** [elastic/ecs-logging#4]
provide ECS formatter for Serilog. 

pinging @Mpdreamz, @russcam & @codebrain

**Comment by codebrain** [comment]
https://github.com/serilog/serilog-sinks-elasticsearch#elasticsearch-formatters

**Comment by codebrain** [comment]
https://github.com/ehsan-maleki/serilog-sinks-elastic-ecs-logstash

**Comment by codebrain** [comment]
Currently working in https://github.com/elastic/ecs-dotnet/tree/master/src/Elastic.CommonSchema.Serilog

**Comment by philkra** [comment]
Ref: https://github.com/elastic/ecs-dotnet/issues/17

**Comment by codebrain** [comment]
Work is now complete.
