### ISSUE TITLE
[META 27] [Ruby] Logger

### ISSUE THREAD

**Issue by philkra** [elastic/ecs-logging#6]
Implement an ECS compliant formatter/layout for ruby lang's [Logger](https://docs.ruby-lang.org/en/2.4.0/Logger.html).

- Create validator of the [spec](https://github.com/elastic/ecs-logging/blob/master/spec/spec.json)
- Fill OSS checklist
- Create docs

**Comment by mikker** [comment]
See https://github.com/elastic/ecs-logging-ruby
